# Generated by Django 5.0.7 on 2026-07-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_phone_number_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
