# Generated by Django 5.0.7 on 2026-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quoterequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for quotes', max_length=15),
        ),
    ]
