# Generated by Django 5.0.7 on 2026-08-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors_variants',
            field=models.CharField(blank=True, help_text='Comma separated colors/variants', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
